config/routes.rb
Rails.application.routes.draw do
  resources :signup, only: [:new, :create]
  # resources :sessions
  resources :home


  resources :users, only: [:create, :show] do
    resources :uploads
  end
  # get "/register", to: "signup#new"
  # get "/signup", to: "signup#create"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"


  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  validates :file, presence: true

  def expiring_url seconds_to_expiry = 20
    bucket = Aws::S3::ExtractsBucket.new
    bucket.presigner.presigned_url :get_object, bucket: ENV["S3_BUCKET"], key: file.key, expires_in: seconds_to_expiry
  end
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt

  has_secure_password

  has_one_attached :avatar

  has_many :uploads

  validates :email_address, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates :avatar, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action do
    ActiveStorage::Current.host = request.base_url
  end

  before_action :authorized, only: [:index]

  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email_address: params[:email_address])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to home_index_path
    else
      render :new
    end
  end

  def destroy
    if session.delete(:user_id)
      redirect_to login_path
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save!
      session[:user_id] = @user.id
      redirect_to home_index_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation, :avatar)
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authorized

  before_action do
    ActiveStorage::Current.host = request.base_url
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params.merge(user_id: current_user.id))
    if @upload.save
      redirect_to user_uploads_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @uploads = current_user.uploads
  end

  def show
    @upload = current_user.uploads.find(params[:id])
    expiring_url = @upload.expiring_url
    Rails.logger.info "******************************"
    Rails.logger.info expiring_url
    Rails.logger.info "******************************"
    redirect_to expiring_url, allow_other_host: true
  end

  private

  def upload_params
    params.require(:upload).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<h1>Welcome to home page of <%= @user.email_address %></h2>

<% if current_user == @user %>
  <h3>My Page!</h3>

  <%# if current_user.avatar.present? %>
    <%#= image_tag current_user.avatar&.url %>
  <%# end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectS3Example</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to 'New Upload', new_user_upload_path(current_user) %>
      <%= link_to 'Uploads', user_uploads_path(current_user) %>

      <%= link_to "Sign Out", sessions_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }  %>
    <% else %>
      <%= link_to 'Sign UP', new_signup_path %>
      <%= link_to 'Sign In', login_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/signup/new.html.erb
<%= form_for @user, url: signup_index_path, method: :post do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :email_address %>
  <%= f.text_field :email_address, placeholder: "Input Email" %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.file_field :avatar %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/uploads/index.html.erb
<table border="1">
  <thead>
    <th>File</th>
  </thead>
  <% @uploads.each_with_index do |upload, i| %>
    <tbody>
      <td><%= i + 1%></td>
      <td><%= image_tag(upload.file.url, height: '50px', width: '50px') %></td>
      <td><%= link_to 'Show', user_upload_path(current_user.id, upload.id) %></td>
    </tbody>
  <% end %> 
</table>

app/views/uploads/new.html.erb
<%= form_for [current_user, @upload] do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@upload.errors.count, "error") %>
      </div>
      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :file %>
  <%= f.submit "Create" %>
<% end %>

app/views/uploads/show.html.erb
<br/>

<%= image_tag(@upload.file.url, height: '100px', width: '100px') %>